debug: false
spring:
  cache:
    type: redis
  datasource:
#    url: jdbc:mysql:///jkpro?useUnicode=true&characterEncoding=UTF8&useSSL=false
#    username: jkpro
#    password: w2tMZHCY4k77CGeG
    url: jdbc:mysql://47.243.112.65:8066/cdbdb?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: Q6TGdDT7fQhGK899
    druid:
      max-active: 50
      initial-size: 5
      min-idle: 5
      # 获取连接时的最大等待时间（毫秒）
      max-wait: 60000
      # 间隔多久检测一次空闲连接（毫秒）
      timeBetweenEvictionRunsMillis: 60000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  # Redis数据库索引（默认为0）
  redis:
    database: 1
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: ny123
    # 连接超时时间（毫秒）
    timeout: 60000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
server:
  #servlet:
    #context-path: /cdb
  tomcat:
    basedir: /jk-flash/runtime/tmp
knife4j:
  # 开启增强模式
  enable: true
  # 开启生产环境保护
  production: false
  basic:
    username: ny
    password: ny
    enable: true
