debug: true
spring:
  cache:
    type: redis
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/cdb_demo?useUnicode=true&characterEncoding=UTF8&useSSL=false
#    username: root
#    password: 123456987
    url: jdbc:mysql://8.210.101.247:3306/cdbdb?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: asd666888!@#
    druid:
      max-active: 50
      initial-size: 5
      min-idle: 5
      # 获取连接时的最大等待时间（毫秒）
      max-wait: 60000
      # 间隔多久检测一次空闲连接（毫秒）
      timeBetweenEvictionRunsMillis: 60000
#    url: jdbc:mysql://rm-3ns18b3ocm140o887co.mysql.rds.aliyuncs.com:3306/testcdb?useUnicode=true&characterEncoding=UTF8&useSSL=false
#    username: testcdb
#    password: asd666888!@#

  #    url: jdbc:mysql://rm-6gjsb3t47439ll70f2o.mysql.ap-south-1.rds.aliyuncs.com/cdbdb?useUnicode=true&characterEncoding=UTF8&useSSL=false
  #    username: cdbdb
  #    password: qq666888!@#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # Redis数据库索引（默认为0）
  redis:
    #    database: 8
    #    # Redis服务器地址
    #    host: 192.168.31.166
    #    # Redis服务器连接端口
    #    port: 6379
    #    # Redis服务器连接密码（默认为空）
    #    password: UxNja^ZYmr$3J7l
    database: 8
    # Redis服务器地址
    host: 8.210.85.148
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456987

    # 连接超时时间（毫秒）
    timeout: 60000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 0
server:
  tomcat:
    basedir: /Users/zx/Documents
knife4j:
  # 开启增强模式
  enable: true
  # 开启生产环境保护
  production: false
  basic:
    username: ny
    password: ny
    enable: true
