spring:
  cache:
    type: redis
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      web-stat-filter:
        enabled: true
        url-pattern: /*
      stat-view-servlet:
        enabled: true
        url-pattern: /*
        reset-enable: false
        login-username: rh
        login-password: rh
        allow: 127.0.0.1
    sql-script-encoding: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      max-file-size: 1000MB
jwt:
  token:
    expire:
      time: 28800
server:
  port: 8082